# Dataset Inspection

High-level structural overview of the entire College Experience Dataset.
Covers file inventory, column inventory, cross-dataset alignment, and student count investigation.

Deep analysis of each data source is in:
- 02_general_EMA_analysis.ipynb
- 03_covid_EMA_analysis.ipynb
- 04_sensing_analysis.ipynb

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)
pd.set_option("display.width", 200)

---
## File Inventory

Scans all files in the raw dataset directory and classifies them by role.
Produces a file inventory saved to outputs/tables/.

In [3]:
DATA_DIR = Path("../../data/raw/college_experience_dataset")
print(DATA_DIR)
print(DATA_DIR.exists())

for f in sorted(DATA_DIR.rglob("*")):
    if f.is_file():
        print(f.name)

..\..\data\raw\college_experience_dataset
True
Data Dictionary.csv
demographics.csv
covid_ema.csv
Data Dictionary (COVID EMA).csv
Data Dictionary (general EMA).csv
general_ema.csv
._calllog.csv
._description.txt
calllog.csv
description.txt
._5e1d4d2718012c036ea65bfe3c80c0e7.csv
._description.txt
0ba15aa0582c5e825710d42fe3eb231d.csv
169d3212668c4eed434dafd32e33c946.csv
17fb1517cc9d7e416782bffb8edd9070.csv
1d2263527eed2a54e88d340fb8e55308.csv
212521733ea8eeff63d997dc0213c692.csv
3528757eaf1d15ee6c778eb79cd02de7.csv
35cf1abf179310dc33907d953f590366.csv
45555d3305e255895b11695c179a98cd.csv
557b44c8daf2ddb5d02313f20f2505b9.csv
5e1d4d2718012c036ea65bfe3c80c0e7.csv
73e13f8273906f7f43a077f95ec48e7d.csv
7d2c632a05bbb03ca97555d61be83c41.csv
862f10a8c357e957a59d122077b3a5ad.csv
9ffbe25e279de21de86acd54b6fa60d0.csv
a52b5e80b4c7a8e05f8cc0a16ae4ea9f.csv
a7a320d21e232075512a494c982dc17f.csv
ac70fe1f8115ac361f2023269c011c3e.csv
aeeb186fafcc356f44cae870555f4a0d.csv
bbcad50219ee8a1484b4c6f000eb4e68.csv
bd6de07de02a8c2e98018a1c7daecc87.csv
c37f9221f44e9ca35a49180dc05a7587.csv
d1075cae00d6198eb840ad42a2df742c.csv
description.txt
f40ed30e72159a5c839a43fe97e0c905.csv
fc26652471ae91bdbbc11a8be89c362c.csv
._description.txt
._smslog.csv
description.txt
smslog.csv
._1df93e607e693903c6fce6054a0a67c5.csv
._3528757eaf1d15ee6c778eb79cd02de7.csv
._8c0c301d93ca93cae5c090caf21816ec.csv
._8ee7d10d8b836222ee69ff04247971a4.csv
._description.txt
003df5deff30e1e5a07b5d063fe85c3f.csv
0107c61e54459068bb83f6be2058d65d.csv
01fb41df0f6c2f69d65db5a38c600b4c.csv
031cf9537e5da78c5a69a10cba088c94.csv
03a0ce5623bfeb8aa3113605f7682215.csv
07eab8e219b6a4dcd45167dc216e1189.csv
0947cdc8e87a0a45a012aa387ccedbcd.csv
0ab7acb36e6c710a7733c1c24e566bb3.csv
0aee9faa6f2d2d24d85d2690f5b2df25.csv
0b9c2303bcc61063f9a5653d77c90501.csv
0ba15aa0582c5e825710d42fe3eb231d.csv
0f2be96bde481cd3898f147a995a7d56.csv
0f727c1018c74fbb7142e8c7a77840d6.csv
107c06248d28377b345ae06e5bda10c1.csv
12e0a85ee9819ae1abeca0ccfaa52d13.csv
12f90c19f2c2b74ec542b62e74e7cad1.csv
13789d5f8a59f1e347e42b99233530d6.csv
1618e7f7049efc1a0fbe48af6fda8e57.csv
165970c3847523de7691ef9766b0f3f4.csv
1741432fb469dbbcd5a40599670c64ce.csv
17fb1517cc9d7e416782bffb8edd9070.csv
1893420fc2b045e14ef0112c1b079afe.csv
1badfae62cc1b76787d4f8beb68737bf.csv
1c12f39481a6c09da17bd4e6bebed9a2.csv
1d0fa4dfa0545bedeaa6045c70b6d19c.csv
1d2263527eed2a54e88d340fb8e55308.csv
1df93e607e693903c6fce6054a0a67c5.csv
1e85c892d8f047ff621ad9134c4e6d8d.csv
1ff6d7f34acb354430e7323a35ff7703.csv
1fff60a0795f79ab1f9432d2cb1f56ee.csv
20b8c420e5a7abcb07f11aab23e42923.csv
212521733ea8eeff63d997dc0213c692.csv
23d00aa2ae3eb2c224734960f2391885.csv
24e89780f6c9efef9ab28fea842cf620.csv
284784fd7319c4e33b0bf1dc90c1a610.csv
2b3d267f18830c3c257b382edabef246.csv
2c4f43b2212eee5ba69563f139911138.csv
2cc3f6274987ee627ab9be37181536eb.csv
2d06da49889845dc3af964bafb630b0a.csv
2d5d41b5e9a9a5bb7007264230e4c575.csv
2de8db6af975b72ac70440ede29e1cfb.csv
2f706716305bceab3969e0f457da16b4.csv
30b497738f121ad199afb509889f6cfe.csv
34ed21e64b190dc037d35ef7f646feb8.csv
3528757eaf1d15ee6c778eb79cd02de7.csv
3569e2f520db9014b4acc4227a6421c1.csv
35cf1abf179310dc33907d953f590366.csv
374d8bd8b755b55ed5a9b08304db6cee.csv
3bb377ba0acb7d8916010184df36aa57.csv
3d1a8b919f65dd22f661468f79b9b107.csv
3dad5f11680b432159b65838119ab87e.csv
3e7ca3545ad22d036db36c4f1e9f2e18.csv
4005a296ac7cd078b8bd56f0b905b7a6.csv
422875809be551a4ec179466aa8300ba.csv
429cf5f822600da91a6f4227c0af86c6.csv
45555d3305e255895b11695c179a98cd.csv
46562035189535f838d640973dbb222e.csv
46b53cdf4d639d54e894d92b6dff817f.csv
46f1dfeda71a865074859c81bb314fd9.csv
480fca3c0b19afab1093cf2f01d63317.csv
4a8ac645226348425b0a43a8373e394d.csv
4b5eb55e64b6bc941796bf114149cab7.csv
4e37495c9c7c8a17e8737e2c61cfe228.csv
4eeb9f06b3ff630aa8f81fd23e1dfe7b.csv
50e32d5c464c892af7aa4b6a666e876d.csv
51ac1dd0849798d75614176ebff633be.csv
54446e36f4601e2c4ab70c355baccc32.csv
546901e10be0157c4fed40c04bfeaaa5.csv
557b44c8daf2ddb5d02313f20f2505b9.csv
5580eba4ad4d1266854f3fec95266bd2.csv
58863d024fc04ff1c3082e2c81e14cf2.csv
59256b077a34f2f4ed7bbf7670e53786.csv
596df3c263e97eb09d44a8535ec20ffa.csv
59cf760cd019690c9007452187578915.csv
5a254d648a95146b403690f81da84bc3.csv
5c446b55e04c641913c09fd39d01d32b.csv
5e1d4d2718012c036ea65bfe3c80c0e7.csv
5e8e425fb65143d25c73b88bd26638eb.csv
5fa34bfca33d0ced12ea991006fbc934.csv
600713d94c8ebe9f12f7d12c6479a131.csv
61f9310e79c30ff4ff836fa065aee93a.csv
6294895f1093b3878b385812d65c3197.csv
62caae288910745b5eb9dde5a9873179.csv
62e43e3420646eaa7ecb44636abda31a.csv
632503a1df16a201a0fc5a1b91d3b01c.csv
63e8142ef2fdd89aec0630ce6070831d.csv
64f2d26b3835e5fa744c35f1709e9c39.csv
6683f5d8f1730b0fce6c1fd8b46ab76f.csv
690d25f3b083e647278ed85c6bb033ae.csv
69d24b22972459bf83ab0c8eb24d13cc.csv
6b0083d00297f9c03e00b2cde889b666.csv
6b22ac2851e90cebdb6bcc50288e031c.csv
6b4ad83b4ee50566e899f3b6c0fb7864.csv
6c4cf48742a55153dd574133a73a6932.csv
6ed487d275984c8c141d40ad10664f46.csv
703c70ff9f0c7a8e24757d0270a2e932.csv
713a6a94988cc13bf0bb50ad0cb0a015.csv
73e13f8273906f7f43a077f95ec48e7d.csv
76b564dca3ab4d899e5a30d3cbcb0aac.csv
791c580346256bca5c697d19170a50b5.csv
79d8490ab94fc7cd6530b1f22593d708.csv
7a5f7cc91bafe10c9708342bb197ea58.csv
7d2c632a05bbb03ca97555d61be83c41.csv
7d41e1ac6994aa87a10a923b31b16cd8.csv
7dcfc929e033d32b768ff4b51bd6a748.csv
7e22b6d9cb821d7004409da02d95cb64.csv
800994037be85bdfd6b3e43be70d02b3.csv
8391d8b451084771d0affcc26e34d773.csv
83a37a7ffd416a2e0a863c86166a97c8.csv
83e4705b8ead02d2659f4d4241183e17.csv
84120765740b5395aa49a2feb12fbb43.csv
8479552e5849c2f93e5f8ab1720ed78b.csv
84875d7ec9c81d58d687aa4805c35c77.csv
8617ddac1f48b148e3683738519b2e7a.csv
86a13f6d0bb7070ca042d60b2a582c4c.csv
8730e74690f38a87355bf45b00fc220e.csv
8733d6d19519598608c6dc2f9ee525d7.csv
87d88cba80cd67d705f61405fbe40da9.csv
8c0c301d93ca93cae5c090caf21816ec.csv
8c644d8cbd193c5575bb826a8abaa245.csv
8c8ee0b0491acee56e6346c2af5c6cf4.csv
8ccf6026d9114437e881d73faa34ea51.csv
8e12cde03a0eaf1a9c41596a81a1cf59.csv
8ee53a46a77476104276e6a1af54472c.csv
8ee7d10d8b836222ee69ff04247971a4.csv
8feafc5db9bf59d00a21335e69b57804.csv
91d30de367a6a0772fdca55ec5b129a2.csv
920e275acd8721dad396513f4d7c99ea.csv
964412e1937376da4b5a70412a600bc9.csv
968356427b2638af0930896c8d4a48d5.csv
96cf40f9d3b2d69466161000cd69ae5c.csv
97487f1632fbab90426f6760a0fe94ea.csv
98e5152e1020930fb007145c1c60648b.csv
993b20b5d910d05b5d79e0de71386a49.csv
9a67ed145c6e7be55b1f744897316f71.csv
9e9e21ee5dbdb37ffda3225cd0403d34.csv
9ffbe25e279de21de86acd54b6fa60d0.csv
a23be0935798553a76b4e74cfc1740f1.csv
a2949761d01e0f82cdbcc71231431959.csv
a4dde9659b38b613f08b37c0c8bfa9eb.csv
a4fcfc9e92d6861285d6c5979d2fd54b.csv
a52b5e80b4c7a8e05f8cc0a16ae4ea9f.csv
a6c1b8b62cc50f9022f018b5198648a0.csv
a7a320d21e232075512a494c982dc17f.csv
a7cb6ba9ef6b3878a4284b0d63afecd7.csv
aa77ecb82c267ad01e9899413f072025.csv
ab5ee451ce580a761fefd88f7b49a97f.csv
ac02afb2367b89fdcab1b1245e195b27.csv
ac23ab17a31d1abeea72e408ac5871c1.csv
ac70fe1f8115ac361f2023269c011c3e.csv
b17eeda399b312140dc40b8445a8e0a5.csv
b1fed5ab5fbd8a1b2fd93b925849a11c.csv
b3db52ffec3adfc49eb061af2f2f2846.csv
b4d5a392109a5d0a0e6da33189e63511.csv
b5dea997cb5e8f17d428c5047a9a1c08.csv
b855dfddb71e240c1990b539533cd1f6.csv
bbcad50219ee8a1484b4c6f000eb4e68.csv
bc3ae668f5930dcab54b63a9cfd0896d.csv
bd441b322153093e69f107a36a9b15d6.csv
bd6de07de02a8c2e98018a1c7daecc87.csv
bdefb86f43d463ae4475291ec837f7d7.csv
bea4c7250c8631ddfacf57dfa386caba.csv
c0b0998fe60a905081764378d1102494.csv
c0fec81b63a711ebc1c29a5df6e21b07.csv
c21283c11daebb61004b688f04c27715.csv
c21d2515be8477a92181b9c0035a9884.csv
c2d80f95e15e8973a9a943564baea1b7.csv
c31fd374e5d8227a31bf8f06f0402b96.csv
c37f9221f44e9ca35a49180dc05a7587.csv
c4de76cb7f30c4073617bfb80fabaec6.csv
c703d4732f997328085fad609ecd6656.csv
c75fc80fba7cbe2b7d9cbc71be5b91a6.csv
c7d47e96f38254e31508ca2c19b24d29.csv
c98557ba920872193b0d6d8d90ac2eb0.csv
cf007be9a060b779cf5a71b3e59a9d5b.csv
d038cb570b5de5840c0677e72d2ba198.csv
d060bfe5da35b9cbd05e3dc33e167092.csv
d1075cae00d6198eb840ad42a2df742c.csv
d1cd5ab675681cd980ee4dd212d8c53c.csv
d2c8a48736cfe925440115558db860ee.csv
d86f28a1830ecec98f00cd0fddf8b1ef.csv
da130c5ecc942e7cd705585222a42adf.csv
db422d4921bbfae5352fdc90cea7bd07.csv
db8df8be53722b041b1e649ae0c0b5d4.csv
dd2ab53554046244203dfb4a72ad4e18.csv
description.txt
df5e798581def8d477316520953b9171.csv
dfba04a156c13a94753a56bbbdd58969.csv
e06024d216d36ef2d7cddc8a67cf77a7.csv
e1b0f11a76278ee3f33e48e2d81b50d0.csv
e3d27e46b8e06963920efb69f95df6fc.csv
e535002d3f0d00b98ff8a34754d6472b.csv
e60e86c5e68c34e34f69aa9257eb977b.csv
e6d71fe4a3c10b075ae1cf51a2fe6cfd.csv
e8811b53add5bfb32640af600ba33399.csv
e946e1f85b5de2dba4edcf1aebbfdc0a.csv
ea716dd032aaa0dcf8bfa36b1811917f.csv
eb5b94ef4672c2971d18f0d95d51f892.csv
f066d6d9013a60a4b65eda0f2518f61a.csv
f0db9e3e8b9b5080e5752383cceb34f6.csv
f17129feb37d5dcec17728f50d7beb95.csv
f1dcebbb6fbe6d586ddb2c43c781e013.csv
f3e1995993cccfe83056a8deb2e315ff.csv
f40ed30e72159a5c839a43fe97e0c905.csv
f4d488e3c8096842b645280d8f01ae43.csv
f5529fbae87a8d170937d3e39d5a63cc.csv
f578948fdf09c92bc603dae7400b6673.csv
f5fa7e56d2303d8b1e3bb33d367c98c5.csv
f663e0d08f34a40d5930a3298bc8e98e.csv
f7472689b3556548c03d3b064d6ab9a8.csv
fa394f6d3d077bd5568fc3bc01580806.csv
fbcc8cd8254960ed44ffdd3390a2f6a0.csv
fc26652471ae91bdbbc11a8be89c362c.csv
fc73375dda5e5460f7088c78654a945e.csv
fe8ddda4ae8c71f7054ca024b82f5c98.csv
ffc4b142e017c162ed4db7b05414fc4b.csv
Readme.md
Data Dictionary (Daily).csv
Data Dictionary (Hourly).csv
sensing.csv
steps.csv

In [4]:
all_files = [f for f in sorted(DATA_DIR.rglob("*")) if f.is_file() and not f.name.startswith("._")]
print("Number of files:", len(all_files))

for f in all_files:
    print(f.relative_to(DATA_DIR))

Number of files: 256
Demographics\Data Dictionary.csv
Demographics\demographics.csv
EMA\covid_ema.csv
EMA\Data Dictionary (COVID EMA).csv
EMA\Data Dictionary (general EMA).csv
EMA\general_ema.csv
Raw Sensing\call_log\calllog.csv
Raw Sensing\call_log\description.txt
Raw Sensing\running_apps\0ba15aa0582c5e825710d42fe3eb231d.csv
Raw Sensing\running_apps\169d3212668c4eed434dafd32e33c946.csv
Raw Sensing\running_apps\17fb1517cc9d7e416782bffb8edd9070.csv
Raw Sensing\running_apps\1d2263527eed2a54e88d340fb8e55308.csv
Raw Sensing\running_apps\212521733ea8eeff63d997dc0213c692.csv
Raw Sensing\running_apps\3528757eaf1d15ee6c778eb79cd02de7.csv
Raw Sensing\running_apps\35cf1abf179310dc33907d953f590366.csv
Raw Sensing\running_apps\45555d3305e255895b11695c179a98cd.csv
Raw Sensing\running_apps\557b44c8daf2ddb5d02313f20f2505b9.csv
Raw Sensing\running_apps\5e1d4d2718012c036ea65bfe3c80c0e7.csv
Raw Sensing\running_apps\73e13f8273906f7f43a077f95ec48e7d.csv
Raw Sensing\running_apps\7d2c632a05bbb03ca97555d61be83c41.csv
Raw Sensing\running_apps\862f10a8c357e957a59d122077b3a5ad.csv
Raw Sensing\running_apps\9ffbe25e279de21de86acd54b6fa60d0.csv
Raw Sensing\running_apps\a52b5e80b4c7a8e05f8cc0a16ae4ea9f.csv
Raw Sensing\running_apps\a7a320d21e232075512a494c982dc17f.csv
Raw Sensing\running_apps\ac70fe1f8115ac361f2023269c011c3e.csv
Raw Sensing\running_apps\aeeb186fafcc356f44cae870555f4a0d.csv
Raw Sensing\running_apps\bbcad50219ee8a1484b4c6f000eb4e68.csv
Raw Sensing\running_apps\bd6de07de02a8c2e98018a1c7daecc87.csv
Raw Sensing\running_apps\c37f9221f44e9ca35a49180dc05a7587.csv
Raw Sensing\running_apps\d1075cae00d6198eb840ad42a2df742c.csv
Raw Sensing\running_apps\description.txt
Raw Sensing\running_apps\f40ed30e72159a5c839a43fe97e0c905.csv
Raw Sensing\running_apps\fc26652471ae91bdbbc11a8be89c362c.csv
Raw Sensing\sms_log\description.txt
Raw Sensing\sms_log\smslog.csv
Raw Sensing\unlock\003df5deff30e1e5a07b5d063fe85c3f.csv
Raw Sensing\unlock\0107c61e54459068bb83f6be2058d65d.csv
Raw Sensing\unlock\01fb41df0f6c2f69d65db5a38c600b4c.csv
Raw Sensing\unlock\031cf9537e5da78c5a69a10cba088c94.csv
Raw Sensing\unlock\03a0ce5623bfeb8aa3113605f7682215.csv
Raw Sensing\unlock\07eab8e219b6a4dcd45167dc216e1189.csv
Raw Sensing\unlock\0947cdc8e87a0a45a012aa387ccedbcd.csv
Raw Sensing\unlock\0ab7acb36e6c710a7733c1c24e566bb3.csv
Raw Sensing\unlock\0aee9faa6f2d2d24d85d2690f5b2df25.csv
Raw Sensing\unlock\0b9c2303bcc61063f9a5653d77c90501.csv
Raw Sensing\unlock\0ba15aa0582c5e825710d42fe3eb231d.csv
Raw Sensing\unlock\0f2be96bde481cd3898f147a995a7d56.csv
Raw Sensing\unlock\0f727c1018c74fbb7142e8c7a77840d6.csv
Raw Sensing\unlock\107c06248d28377b345ae06e5bda10c1.csv
Raw Sensing\unlock\12e0a85ee9819ae1abeca0ccfaa52d13.csv
Raw Sensing\unlock\12f90c19f2c2b74ec542b62e74e7cad1.csv
Raw Sensing\unlock\13789d5f8a59f1e347e42b99233530d6.csv
Raw Sensing\unlock\1618e7f7049efc1a0fbe48af6fda8e57.csv
Raw Sensing\unlock\165970c3847523de7691ef9766b0f3f4.csv
Raw Sensing\unlock\1741432fb469dbbcd5a40599670c64ce.csv
Raw Sensing\unlock\17fb1517cc9d7e416782bffb8edd9070.csv
Raw Sensing\unlock\1893420fc2b045e14ef0112c1b079afe.csv
Raw Sensing\unlock\1badfae62cc1b76787d4f8beb68737bf.csv
Raw Sensing\unlock\1c12f39481a6c09da17bd4e6bebed9a2.csv
Raw Sensing\unlock\1d0fa4dfa0545bedeaa6045c70b6d19c.csv
Raw Sensing\unlock\1d2263527eed2a54e88d340fb8e55308.csv
Raw Sensing\unlock\1df93e607e693903c6fce6054a0a67c5.csv
Raw Sensing\unlock\1e85c892d8f047ff621ad9134c4e6d8d.csv
Raw Sensing\unlock\1ff6d7f34acb354430e7323a35ff7703.csv
Raw Sensing\unlock\1fff60a0795f79ab1f9432d2cb1f56ee.csv
Raw Sensing\unlock\20b8c420e5a7abcb07f11aab23e42923.csv
Raw Sensing\unlock\212521733ea8eeff63d997dc0213c692.csv
Raw Sensing\unlock\23d00aa2ae3eb2c224734960f2391885.csv
Raw Sensing\unlock\24e89780f6c9efef9ab28fea842cf620.csv
Raw Sensing\unlock\284784fd7319c4e33b0bf1dc90c1a610.csv
Raw Sensing\unlock\2b3d267f18830c3c257b382edabef246.csv
Raw Sensing\unlock\2c4f43b2212eee5ba69563f139911138.csv
Raw Sensing\unlock\2cc3f6274987ee627ab9be37181536eb.csv
Raw Sensing\unlock\2d06da49889845dc3af964bafb630b0a.csv
Raw Sensing\unlock\2d5d41b5e9a9a5bb7007264230e4c575.csv
Raw Sensing\unlock\2de8db6af975b72ac70440ede29e1cfb.csv
Raw Sensing\unlock\2f706716305bceab3969e0f457da16b4.csv
Raw Sensing\unlock\30b497738f121ad199afb509889f6cfe.csv
Raw Sensing\unlock\34ed21e64b190dc037d35ef7f646feb8.csv
Raw Sensing\unlock\3528757eaf1d15ee6c778eb79cd02de7.csv
Raw Sensing\unlock\3569e2f520db9014b4acc4227a6421c1.csv
Raw Sensing\unlock\35cf1abf179310dc33907d953f590366.csv
Raw Sensing\unlock\374d8bd8b755b55ed5a9b08304db6cee.csv
Raw Sensing\unlock\3bb377ba0acb7d8916010184df36aa57.csv
Raw Sensing\unlock\3d1a8b919f65dd22f661468f79b9b107.csv
Raw Sensing\unlock\3dad5f11680b432159b65838119ab87e.csv
Raw Sensing\unlock\3e7ca3545ad22d036db36c4f1e9f2e18.csv
Raw Sensing\unlock\4005a296ac7cd078b8bd56f0b905b7a6.csv
Raw Sensing\unlock\422875809be551a4ec179466aa8300ba.csv
Raw Sensing\unlock\429cf5f822600da91a6f4227c0af86c6.csv
Raw Sensing\unlock\45555d3305e255895b11695c179a98cd.csv
Raw Sensing\unlock\46562035189535f838d640973dbb222e.csv
Raw Sensing\unlock\46b53cdf4d639d54e894d92b6dff817f.csv
Raw Sensing\unlock\46f1dfeda71a865074859c81bb314fd9.csv
Raw Sensing\unlock\480fca3c0b19afab1093cf2f01d63317.csv
Raw Sensing\unlock\4a8ac645226348425b0a43a8373e394d.csv
Raw Sensing\unlock\4b5eb55e64b6bc941796bf114149cab7.csv
Raw Sensing\unlock\4e37495c9c7c8a17e8737e2c61cfe228.csv
Raw Sensing\unlock\4eeb9f06b3ff630aa8f81fd23e1dfe7b.csv
Raw Sensing\unlock\50e32d5c464c892af7aa4b6a666e876d.csv
Raw Sensing\unlock\51ac1dd0849798d75614176ebff633be.csv
Raw Sensing\unlock\54446e36f4601e2c4ab70c355baccc32.csv
Raw Sensing\unlock\546901e10be0157c4fed40c04bfeaaa5.csv
Raw Sensing\unlock\557b44c8daf2ddb5d02313f20f2505b9.csv
Raw Sensing\unlock\5580eba4ad4d1266854f3fec95266bd2.csv
Raw Sensing\unlock\58863d024fc04ff1c3082e2c81e14cf2.csv
Raw Sensing\unlock\59256b077a34f2f4ed7bbf7670e53786.csv
Raw Sensing\unlock\596df3c263e97eb09d44a8535ec20ffa.csv
Raw Sensing\unlock\59cf760cd019690c9007452187578915.csv
Raw Sensing\unlock\5a254d648a95146b403690f81da84bc3.csv
Raw Sensing\unlock\5c446b55e04c641913c09fd39d01d32b.csv
Raw Sensing\unlock\5e1d4d2718012c036ea65bfe3c80c0e7.csv
Raw Sensing\unlock\5e8e425fb65143d25c73b88bd26638eb.csv
Raw Sensing\unlock\5fa34bfca33d0ced12ea991006fbc934.csv
Raw Sensing\unlock\600713d94c8ebe9f12f7d12c6479a131.csv
Raw Sensing\unlock\61f9310e79c30ff4ff836fa065aee93a.csv
Raw Sensing\unlock\6294895f1093b3878b385812d65c3197.csv
Raw Sensing\unlock\62caae288910745b5eb9dde5a9873179.csv
Raw Sensing\unlock\62e43e3420646eaa7ecb44636abda31a.csv
Raw Sensing\unlock\632503a1df16a201a0fc5a1b91d3b01c.csv
Raw Sensing\unlock\63e8142ef2fdd89aec0630ce6070831d.csv
Raw Sensing\unlock\64f2d26b3835e5fa744c35f1709e9c39.csv
Raw Sensing\unlock\6683f5d8f1730b0fce6c1fd8b46ab76f.csv
Raw Sensing\unlock\690d25f3b083e647278ed85c6bb033ae.csv
Raw Sensing\unlock\69d24b22972459bf83ab0c8eb24d13cc.csv
Raw Sensing\unlock\6b0083d00297f9c03e00b2cde889b666.csv
Raw Sensing\unlock\6b22ac2851e90cebdb6bcc50288e031c.csv
Raw Sensing\unlock\6b4ad83b4ee50566e899f3b6c0fb7864.csv
Raw Sensing\unlock\6c4cf48742a55153dd574133a73a6932.csv
Raw Sensing\unlock\6ed487d275984c8c141d40ad10664f46.csv
Raw Sensing\unlock\703c70ff9f0c7a8e24757d0270a2e932.csv
Raw Sensing\unlock\713a6a94988cc13bf0bb50ad0cb0a015.csv
Raw Sensing\unlock\73e13f8273906f7f43a077f95ec48e7d.csv
Raw Sensing\unlock\76b564dca3ab4d899e5a30d3cbcb0aac.csv
Raw Sensing\unlock\791c580346256bca5c697d19170a50b5.csv
Raw Sensing\unlock\79d8490ab94fc7cd6530b1f22593d708.csv
Raw Sensing\unlock\7a5f7cc91bafe10c9708342bb197ea58.csv
Raw Sensing\unlock\7d2c632a05bbb03ca97555d61be83c41.csv
Raw Sensing\unlock\7d41e1ac6994aa87a10a923b31b16cd8.csv
Raw Sensing\unlock\7dcfc929e033d32b768ff4b51bd6a748.csv
Raw Sensing\unlock\7e22b6d9cb821d7004409da02d95cb64.csv
Raw Sensing\unlock\800994037be85bdfd6b3e43be70d02b3.csv
Raw Sensing\unlock\8391d8b451084771d0affcc26e34d773.csv
Raw Sensing\unlock\83a37a7ffd416a2e0a863c86166a97c8.csv
Raw Sensing\unlock\83e4705b8ead02d2659f4d4241183e17.csv
Raw Sensing\unlock\84120765740b5395aa49a2feb12fbb43.csv
Raw Sensing\unlock\8479552e5849c2f93e5f8ab1720ed78b.csv
Raw Sensing\unlock\84875d7ec9c81d58d687aa4805c35c77.csv
Raw Sensing\unlock\8617ddac1f48b148e3683738519b2e7a.csv
Raw Sensing\unlock\86a13f6d0bb7070ca042d60b2a582c4c.csv
Raw Sensing\unlock\8730e74690f38a87355bf45b00fc220e.csv
Raw Sensing\unlock\8733d6d19519598608c6dc2f9ee525d7.csv
Raw Sensing\unlock\87d88cba80cd67d705f61405fbe40da9.csv
Raw Sensing\unlock\8c0c301d93ca93cae5c090caf21816ec.csv
Raw Sensing\unlock\8c644d8cbd193c5575bb826a8abaa245.csv
Raw Sensing\unlock\8c8ee0b0491acee56e6346c2af5c6cf4.csv
Raw Sensing\unlock\8ccf6026d9114437e881d73faa34ea51.csv
Raw Sensing\unlock\8e12cde03a0eaf1a9c41596a81a1cf59.csv
Raw Sensing\unlock\8ee53a46a77476104276e6a1af54472c.csv
Raw Sensing\unlock\8ee7d10d8b836222ee69ff04247971a4.csv
Raw Sensing\unlock\8feafc5db9bf59d00a21335e69b57804.csv
Raw Sensing\unlock\91d30de367a6a0772fdca55ec5b129a2.csv
Raw Sensing\unlock\920e275acd8721dad396513f4d7c99ea.csv
Raw Sensing\unlock\964412e1937376da4b5a70412a600bc9.csv
Raw Sensing\unlock\968356427b2638af0930896c8d4a48d5.csv
Raw Sensing\unlock\96cf40f9d3b2d69466161000cd69ae5c.csv
Raw Sensing\unlock\97487f1632fbab90426f6760a0fe94ea.csv
Raw Sensing\unlock\98e5152e1020930fb007145c1c60648b.csv
Raw Sensing\unlock\993b20b5d910d05b5d79e0de71386a49.csv
Raw Sensing\unlock\9a67ed145c6e7be55b1f744897316f71.csv
Raw Sensing\unlock\9e9e21ee5dbdb37ffda3225cd0403d34.csv
Raw Sensing\unlock\9ffbe25e279de21de86acd54b6fa60d0.csv
Raw Sensing\unlock\a23be0935798553a76b4e74cfc1740f1.csv
Raw Sensing\unlock\a2949761d01e0f82cdbcc71231431959.csv
Raw Sensing\unlock\a4dde9659b38b613f08b37c0c8bfa9eb.csv
Raw Sensing\unlock\a4fcfc9e92d6861285d6c5979d2fd54b.csv
Raw Sensing\unlock\a52b5e80b4c7a8e05f8cc0a16ae4ea9f.csv
Raw Sensing\unlock\a6c1b8b62cc50f9022f018b5198648a0.csv
Raw Sensing\unlock\a7a320d21e232075512a494c982dc17f.csv
Raw Sensing\unlock\a7cb6ba9ef6b3878a4284b0d63afecd7.csv
Raw Sensing\unlock\aa77ecb82c267ad01e9899413f072025.csv
Raw Sensing\unlock\ab5ee451ce580a761fefd88f7b49a97f.csv
Raw Sensing\unlock\ac02afb2367b89fdcab1b1245e195b27.csv
Raw Sensing\unlock\ac23ab17a31d1abeea72e408ac5871c1.csv
Raw Sensing\unlock\ac70fe1f8115ac361f2023269c011c3e.csv
Raw Sensing\unlock\b17eeda399b312140dc40b8445a8e0a5.csv
Raw Sensing\unlock\b1fed5ab5fbd8a1b2fd93b925849a11c.csv
Raw Sensing\unlock\b3db52ffec3adfc49eb061af2f2f2846.csv
Raw Sensing\unlock\b4d5a392109a5d0a0e6da33189e63511.csv
Raw Sensing\unlock\b5dea997cb5e8f17d428c5047a9a1c08.csv
Raw Sensing\unlock\b855dfddb71e240c1990b539533cd1f6.csv
Raw Sensing\unlock\bbcad50219ee8a1484b4c6f000eb4e68.csv
Raw Sensing\unlock\bc3ae668f5930dcab54b63a9cfd0896d.csv
Raw Sensing\unlock\bd441b322153093e69f107a36a9b15d6.csv
Raw Sensing\unlock\bd6de07de02a8c2e98018a1c7daecc87.csv
Raw Sensing\unlock\bdefb86f43d463ae4475291ec837f7d7.csv
Raw Sensing\unlock\bea4c7250c8631ddfacf57dfa386caba.csv
Raw Sensing\unlock\c0b0998fe60a905081764378d1102494.csv
Raw Sensing\unlock\c0fec81b63a711ebc1c29a5df6e21b07.csv
Raw Sensing\unlock\c21283c11daebb61004b688f04c27715.csv
Raw Sensing\unlock\c21d2515be8477a92181b9c0035a9884.csv
Raw Sensing\unlock\c2d80f95e15e8973a9a943564baea1b7.csv
Raw Sensing\unlock\c31fd374e5d8227a31bf8f06f0402b96.csv
Raw Sensing\unlock\c37f9221f44e9ca35a49180dc05a7587.csv
Raw Sensing\unlock\c4de76cb7f30c4073617bfb80fabaec6.csv
Raw Sensing\unlock\c703d4732f997328085fad609ecd6656.csv
Raw Sensing\unlock\c75fc80fba7cbe2b7d9cbc71be5b91a6.csv
Raw Sensing\unlock\c7d47e96f38254e31508ca2c19b24d29.csv
Raw Sensing\unlock\c98557ba920872193b0d6d8d90ac2eb0.csv
Raw Sensing\unlock\cf007be9a060b779cf5a71b3e59a9d5b.csv
Raw Sensing\unlock\d038cb570b5de5840c0677e72d2ba198.csv
Raw Sensing\unlock\d060bfe5da35b9cbd05e3dc33e167092.csv
Raw Sensing\unlock\d1075cae00d6198eb840ad42a2df742c.csv
Raw Sensing\unlock\d1cd5ab675681cd980ee4dd212d8c53c.csv
Raw Sensing\unlock\d2c8a48736cfe925440115558db860ee.csv
Raw Sensing\unlock\d86f28a1830ecec98f00cd0fddf8b1ef.csv
Raw Sensing\unlock\da130c5ecc942e7cd705585222a42adf.csv
Raw Sensing\unlock\db422d4921bbfae5352fdc90cea7bd07.csv
Raw Sensing\unlock\db8df8be53722b041b1e649ae0c0b5d4.csv
Raw Sensing\unlock\dd2ab53554046244203dfb4a72ad4e18.csv
Raw Sensing\unlock\description.txt
Raw Sensing\unlock\df5e798581def8d477316520953b9171.csv
Raw Sensing\unlock\dfba04a156c13a94753a56bbbdd58969.csv
Raw Sensing\unlock\e06024d216d36ef2d7cddc8a67cf77a7.csv
Raw Sensing\unlock\e1b0f11a76278ee3f33e48e2d81b50d0.csv
Raw Sensing\unlock\e3d27e46b8e06963920efb69f95df6fc.csv
Raw Sensing\unlock\e535002d3f0d00b98ff8a34754d6472b.csv
Raw Sensing\unlock\e60e86c5e68c34e34f69aa9257eb977b.csv
Raw Sensing\unlock\e6d71fe4a3c10b075ae1cf51a2fe6cfd.csv
Raw Sensing\unlock\e8811b53add5bfb32640af600ba33399.csv
Raw Sensing\unlock\e946e1f85b5de2dba4edcf1aebbfdc0a.csv
Raw Sensing\unlock\ea716dd032aaa0dcf8bfa36b1811917f.csv
Raw Sensing\unlock\eb5b94ef4672c2971d18f0d95d51f892.csv
Raw Sensing\unlock\f066d6d9013a60a4b65eda0f2518f61a.csv
Raw Sensing\unlock\f0db9e3e8b9b5080e5752383cceb34f6.csv
Raw Sensing\unlock\f17129feb37d5dcec17728f50d7beb95.csv
Raw Sensing\unlock\f1dcebbb6fbe6d586ddb2c43c781e013.csv
Raw Sensing\unlock\f3e1995993cccfe83056a8deb2e315ff.csv
Raw Sensing\unlock\f40ed30e72159a5c839a43fe97e0c905.csv
Raw Sensing\unlock\f4d488e3c8096842b645280d8f01ae43.csv
Raw Sensing\unlock\f5529fbae87a8d170937d3e39d5a63cc.csv
Raw Sensing\unlock\f578948fdf09c92bc603dae7400b6673.csv
Raw Sensing\unlock\f5fa7e56d2303d8b1e3bb33d367c98c5.csv
Raw Sensing\unlock\f663e0d08f34a40d5930a3298bc8e98e.csv
Raw Sensing\unlock\f7472689b3556548c03d3b064d6ab9a8.csv
Raw Sensing\unlock\fa394f6d3d077bd5568fc3bc01580806.csv
Raw Sensing\unlock\fbcc8cd8254960ed44ffdd3390a2f6a0.csv
Raw Sensing\unlock\fc26652471ae91bdbbc11a8be89c362c.csv
Raw Sensing\unlock\fc73375dda5e5460f7088c78654a945e.csv
Raw Sensing\unlock\fe8ddda4ae8c71f7054ca024b82f5c98.csv
Raw Sensing\unlock\ffc4b142e017c162ed4db7b05414fc4b.csv
Readme.md
Sensing\Data Dictionary (Daily).csv
Sensing\Data Dictionary (Hourly).csv
Sensing\sensing.csv
Sensing\steps.csv

In [5]:
inventory = pd.DataFrame({
    "file_name": [f.name for f in all_files],
    "relative_path": [str(f.relative_to(DATA_DIR)) for f in all_files],
    "suffix": [f.suffix.lower() for f in all_files],
    "size_bytes": [f.stat().st_size for f in all_files],
})

inventory["path_parts"] = inventory["relative_path"].apply(lambda x: x.replace("\\", "/").split("/"))
inventory["top_level_group"] = inventory["path_parts"].apply(lambda x: x[0] if len(x) > 0 else None)
inventory["subgroup"] = inventory["path_parts"].apply(lambda x: x[1] if len(x) > 1 else None)

inventory.head()

                           file_name                          relative_path suffix  size_bytes                                path_parts top_level_group                           subgroup
0                Data Dictionary.csv       Demographics\Data Dictionary.csv   .csv         133       [Demographics, Data Dictionary.csv]    Demographics                Data Dictionary.csv
1                   demographics.csv          Demographics\demographics.csv   .csv        9088          [Demographics, demographics.csv]    Demographics                   demographics.csv
2                      covid_ema.csv                      EMA\covid_ema.csv   .csv     1027081                      [EMA, covid_ema.csv]             EMA                      covid_ema.csv
3    Data Dictionary (COVID EMA).csv    EMA\Data Dictionary (COVID EMA).csv   .csv        1489    [EMA, Data Dictionary (COVID EMA).csv]             EMA    Data Dictionary (COVID EMA).csv
4  Data Dictionary (general EMA).csv  EMA\Data Dictionary (general EMA).csv   .csv        2890  [EMA, Data Dictionary (general EMA).csv]             EMA  Data Dictionary (general EMA).csv

In [6]:
suffix_counts = (
    inventory.groupby("suffix")
    .size()
    .reset_index(name="file_count")
    .sort_values("file_count", ascending=False)
)

suffix_counts

  suffix  file_count
0   .csv         251
2   .txt           4
1    .md           1

In [7]:
output_tables = Path("../../outputs/tables")
output_tables.mkdir(parents=True, exist_ok=True)

suffix_counts.to_csv(output_tables / "file_counts_by_suffix.csv", index=False)

In [8]:
def guess_role(relative_path: str) -> str:
    path_lower = relative_path.lower()
    
    if "dictionary" in path_lower:
        return "dictionary"
    if "ema" in path_lower:
        return "label_or_survey"
    if "demographics" in path_lower:
        return "metadata"
    if "raw sensing" in path_lower:
        return "sensor"
    return "unknown"

inventory["role_guess"] = inventory["relative_path"].apply(guess_role)
inventory = inventory.drop(columns=["path_parts"], errors="ignore")

inventory.sort_values(["top_level_group", "subgroup", "file_name"]).head(50)

                               file_name                                      relative_path suffix  size_bytes top_level_group                           subgroup       role_guess
0                    Data Dictionary.csv                   Demographics\Data Dictionary.csv   .csv         133    Demographics                Data Dictionary.csv       dictionary
1                       demographics.csv                      Demographics\demographics.csv   .csv        9088    Demographics                   demographics.csv         metadata
3        Data Dictionary (COVID EMA).csv                EMA\Data Dictionary (COVID EMA).csv   .csv        1489             EMA    Data Dictionary (COVID EMA).csv       dictionary
4      Data Dictionary (general EMA).csv              EMA\Data Dictionary (general EMA).csv   .csv        2890             EMA  Data Dictionary (general EMA).csv       dictionary
2                          covid_ema.csv                                  EMA\covid_ema.csv   .csv     1027081             EMA                      covid_ema.csv  label_or_survey
5                        general_ema.csv                                EMA\general_ema.csv   .csv    16449907             EMA                    general_ema.csv  label_or_survey
6                            calllog.csv                   Raw Sensing\call_log\calllog.csv   .csv    16109148     Raw Sensing                           call_log           sensor
7                        description.txt               Raw Sensing\call_log\description.txt   .txt         404     Raw Sensing                           call_log           sensor
8   0ba15aa0582c5e825710d42fe3eb231d.csv  Raw Sensing\running_apps\0ba15aa0582c5e825710d...   .csv     8977666     Raw Sensing                       running_apps           sensor
9   169d3212668c4eed434dafd32e33c946.csv  Raw Sensing\running_apps\169d3212668c4eed434da...   .csv     2645190     Raw Sensing                       running_apps           sensor
10  17fb1517cc9d7e416782bffb8edd9070.csv  Raw Sensing\running_apps\17fb1517cc9d7e416782b...   .csv     1400962     Raw Sensing                       running_apps           sensor
11  1d2263527eed2a54e88d340fb8e55308.csv  Raw Sensing\running_apps\1d2263527eed2a54e88d3...   .csv     3540793     Raw Sensing                       running_apps           sensor
12  212521733ea8eeff63d997dc0213c692.csv  Raw Sensing\running_apps\212521733ea8eeff63d99...   .csv        3574     Raw Sensing                       running_apps           sensor
13  3528757eaf1d15ee6c778eb79cd02de7.csv  Raw Sensing\running_apps\3528757eaf1d15ee6c778...   .csv      417465     Raw Sensing                       running_apps           sensor
14  35cf1abf179310dc33907d953f590366.csv  Raw Sensing\running_apps\35cf1abf179310dc33907...   .csv     1051171     Raw Sensing                       running_apps           sensor
15  45555d3305e255895b11695c179a98cd.csv  Raw Sensing\running_apps\45555d3305e255895b116...   .csv     5699000     Raw Sensing                       running_apps           sensor
16  557b44c8daf2ddb5d02313f20f2505b9.csv  Raw Sensing\running_apps\557b44c8daf2ddb5d0231...   .csv      155980     Raw Sensing                       running_apps           sensor
17  5e1d4d2718012c036ea65bfe3c80c0e7.csv  Raw Sensing\running_apps\5e1d4d2718012c036ea65...   .csv       91205     Raw Sensing                       running_apps           sensor
18  73e13f8273906f7f43a077f95ec48e7d.csv  Raw Sensing\running_apps\73e13f8273906f7f43a07...   .csv     3563923     Raw Sensing                       running_apps           sensor
19  7d2c632a05bbb03ca97555d61be83c41.csv  Raw Sensing\running_apps\7d2c632a05bbb03ca9755...   .csv     8512652     Raw Sensing                       running_apps           sensor
20  862f10a8c357e957a59d122077b3a5ad.csv  Raw Sensing\running_apps\862f10a8c357e957a59d1...   .csv     2865192     Raw Sensing                       running_apps           sensor
21  9ffbe25e279de21de86acd54b6fa60d0.csv  Raw Sensing\running_apps\9ffbe25e279de21de86ac...   .csv       63189     Raw Sensing                       running_apps           sensor
22  a52b5e80b4c7a8e05f8cc0a16ae4ea9f.csv  Raw Sensing\running_apps\a52b5e80b4c7a8e05f8cc...   .csv      275772     Raw Sensing                       running_apps           sensor
23  a7a320d21e232075512a494c982dc17f.csv  Raw Sensing\running_apps\a7a320d21e232075512a4...   .csv     1484891     Raw Sensing                       running_apps           sensor
24  ac70fe1f8115ac361f2023269c011c3e.csv  Raw Sensing\running_apps\ac70fe1f8115ac361f202...   .csv      466766     Raw Sensing                       running_apps           sensor
25  aeeb186fafcc356f44cae870555f4a0d.csv  Raw Sensing\running_apps\aeeb186fafcc356f44cae...   .csv     5797048     Raw Sensing                       running_apps           sensor
26  bbcad50219ee8a1484b4c6f000eb4e68.csv  Raw Sensing\running_apps\bbcad50219ee8a1484b4c...   .csv     1741560     Raw Sensing                       running_apps           sensor
27  bd6de07de02a8c2e98018a1c7daecc87.csv  Raw Sensing\running_apps\bd6de07de02a8c2e98018...   .csv     4018024     Raw Sensing                       running_apps           sensor
28  c37f9221f44e9ca35a49180dc05a7587.csv  Raw Sensing\running_apps\c37f9221f44e9ca35a491...   .csv     5596286     Raw Sensing                       running_apps           sensor
29  d1075cae00d6198eb840ad42a2df742c.csv  Raw Sensing\running_apps\d1075cae00d6198eb840a...   .csv     5479231     Raw Sensing                       running_apps           sensor
30                       description.txt           Raw Sensing\running_apps\description.txt   .txt         114     Raw Sensing                       running_apps           sensor
31  f40ed30e72159a5c839a43fe97e0c905.csv  Raw Sensing\running_apps\f40ed30e72159a5c839a4...   .csv     2403814     Raw Sensing                       running_apps           sensor
32  fc26652471ae91bdbbc11a8be89c362c.csv  Raw Sensing\running_apps\fc26652471ae91bdbbc11...   .csv     5430446     Raw Sensing                       running_apps           sensor
33                       description.txt                Raw Sensing\sms_log\description.txt   .txt         288     Raw Sensing                            sms_log           sensor
34                            smslog.csv                     Raw Sensing\sms_log\smslog.csv   .csv   147895613     Raw Sensing                            sms_log           sensor
35  003df5deff30e1e5a07b5d063fe85c3f.csv  Raw Sensing\unlock\003df5deff30e1e5a07b5d063fe...   .csv     8198595     Raw Sensing                             unlock           sensor
36  0107c61e54459068bb83f6be2058d65d.csv  Raw Sensing\unlock\0107c61e54459068bb83f6be205...   .csv    13219436     Raw Sensing                             unlock           sensor
37  01fb41df0f6c2f69d65db5a38c600b4c.csv  Raw Sensing\unlock\01fb41df0f6c2f69d65db5a38c6...   .csv      532312     Raw Sensing                             unlock           sensor
38  031cf9537e5da78c5a69a10cba088c94.csv  Raw Sensing\unlock\031cf9537e5da78c5a69a10cba0...   .csv     4587677     Raw Sensing                             unlock           sensor
39  03a0ce5623bfeb8aa3113605f7682215.csv  Raw Sensing\unlock\03a0ce5623bfeb8aa3113605f76...   .csv    15926297     Raw Sensing                             unlock           sensor
40  07eab8e219b6a4dcd45167dc216e1189.csv  Raw Sensing\unlock\07eab8e219b6a4dcd45167dc216...   .csv      858110     Raw Sensing                             unlock           sensor
41  0947cdc8e87a0a45a012aa387ccedbcd.csv  Raw Sensing\unlock\0947cdc8e87a0a45a012aa387cc...   .csv     8285030     Raw Sensing                             unlock           sensor
42  0ab7acb36e6c710a7733c1c24e566bb3.csv  Raw Sensing\unlock\0ab7acb36e6c710a7733c1c24e5...   .csv    11124700     Raw Sensing                             unlock           sensor
43  0aee9faa6f2d2d24d85d2690f5b2df25.csv  Raw Sensing\unlock\0aee9faa6f2d2d24d85d2690f5b...   .csv     6369005     Raw Sensing                             unlock           sensor
44  0b9c2303bcc61063f9a5653d77c90501.csv  Raw Sensing\unlock\0b9c2303bcc61063f9a5653d77c...   .csv    15624866     Raw Sensing                             unlock           sensor
45  0ba15aa0582c5e825710d42fe3eb231d.csv  Raw Sensing\unlock\0ba15aa0582c5e825710d42fe3e...   .csv    11848984     Raw Sensing                             unlock           sensor
46  0f2be96bde481cd3898f147a995a7d56.csv  Raw Sensing\unlock\0f2be96bde481cd3898f147a995...   .csv    20283152     Raw Sensing                             unlock           sensor
47  0f727c1018c74fbb7142e8c7a77840d6.csv  Raw Sensing\unlock\0f727c1018c74fbb7142e8c7a77...   .csv     9473821     Raw Sensing                             unlock           sensor
48  107c06248d28377b345ae06e5bda10c1.csv  Raw Sensing\unlock\107c06248d28377b345ae06e5bd...   .csv     7468647     Raw Sensing                             unlock           sensor
49  12e0a85ee9819ae1abeca0ccfaa52d13.csv  Raw Sensing\unlock\12e0a85ee9819ae1abeca0ccfaa...   .csv     5833462     Raw Sensing                             unlock           sensor

In [9]:
role_counts = (
    inventory.groupby("role_guess")
    .size()
    .reset_index(name="file_count")
    .sort_values("file_count", ascending=False)
)

role_counts

        role_guess  file_count
3           sensor         245
0       dictionary           5
4          unknown           3
1  label_or_survey           2
2         metadata           1

In [10]:
inventory.to_csv(output_tables / "file_inventory.csv", index=False)
role_counts.to_csv(output_tables / "file_counts_by_role.csv", index=False)

---
## Column Inventory

Loads the key data files and records every column name, dtype, null count,
and sample value. Covers demographics, EMA files, and sensing.
Saved to outputs/tables/column_inventory.csv.

In [11]:
def load_table(path: Path):
    suffix = path.suffix.lower()
    if suffix == ".csv":
        return pd.read_csv(path)
    elif suffix in [".xlsx", ".xls"]:
        return pd.read_excel(path)
    else:
        raise ValueError(f"Unsupported file type: {suffix}")

In [12]:
important_files = [
    DATA_DIR / "Demographics" / "demographics.csv",
    DATA_DIR / "Demographics" / "Data Dictionary.csv",
    DATA_DIR / "EMA" / "general_ema.csv",
    DATA_DIR / "EMA" / "Data Dictionary (general EMA).csv",
    DATA_DIR / "EMA" / "covid_ema.csv",
    DATA_DIR / "EMA" / "Data Dictionary (COVID EMA).csv",
    DATA_DIR / "Sensing" / "sensing.csv",
]

In [13]:
column_inventory_rows = []

for path in important_files:
    if not path.exists():
        print(f"Missing: {path}")
        continue
        
    df = load_table(path)
    
    for col in df.columns:
        series = df[col]
        column_inventory_rows.append({
            "file_name": path.name,
            "relative_path": str(path.relative_to(DATA_DIR)),
            "column_name": col,
            "dtype": str(series.dtype),
            "null_count": int(series.isna().sum()),
            "null_pct": float(series.isna().mean()),
            "n_unique": int(series.nunique(dropna=True)),
            "sample_value_1": str(series.dropna().iloc[0]) if series.dropna().shape[0] > 0 else None,
        })

column_inventory = pd.DataFrame(column_inventory_rows)
column_inventory.head(30)

                            file_name                          relative_path                               column_name    dtype  null_count  null_pct  n_unique                    sample_value_1
0                    demographics.csv          Demographics\demographics.csv                                       uid      str           0  0.000000       216  3569e2f520db9014b4acc4227a6421c1
1                    demographics.csv          Demographics\demographics.csv                                    gender      str           0  0.000000         3                              both
2                    demographics.csv          Demographics\demographics.csv                                      race      str           0  0.000000         8                             white
3                 Data Dictionary.csv       Demographics\Data Dictionary.csv                                  Variable      str           0  0.000000         3                               uid
4                 Data Dictionary.csv       Demographics\Data Dictionary.csv                                Definition      str           0  0.000000         3                    Unique user ID
5                     general_ema.csv                    EMA\general_ema.csv                                       uid      str           0  0.000000       220  1ff6d7f34acb354430e7323a35ff7703
6                     general_ema.csv                    EMA\general_ema.csv                                       day    int64           0  0.000000      1762                          20170907
7                     general_ema.csv                    EMA\general_ema.csv                                       pam  float64      181969  0.837968        16                               7.0
8                     general_ema.csv                    EMA\general_ema.csv                                    phq4-1  float64      181807  0.837222         4                               2.0
9                     general_ema.csv                    EMA\general_ema.csv                                    phq4-2  float64      181807  0.837222         4                               2.0
10                    general_ema.csv                    EMA\general_ema.csv                                    phq4-3  float64      181807  0.837222         4                               2.0
11                    general_ema.csv                    EMA\general_ema.csv                                    phq4-4  float64      181807  0.837222         4                               1.0
12                    general_ema.csv                    EMA\general_ema.csv                            phq4_resp_mean  float64      181807  0.837222     34398                     4.49427974224
13                    general_ema.csv                    EMA\general_ema.csv                          phq4_resp_median  float64      181807  0.837222     33120                     4.40922439098
14                    general_ema.csv                    EMA\general_ema.csv                                phq4_score  float64      181807  0.837222        13                               7.0
15                    general_ema.csv                    EMA\general_ema.csv                              social_level  float64      181807  0.837222         5                               4.0
16                    general_ema.csv                    EMA\general_ema.csv                                    sse3-1  float64      181807  0.837222         5                               1.0
17                    general_ema.csv                    EMA\general_ema.csv                                    sse3-2  float64      181807  0.837222         5                               3.0
18                    general_ema.csv                    EMA\general_ema.csv                                    sse3-3  float64      181807  0.837222         5                               3.0
19                    general_ema.csv                    EMA\general_ema.csv                                    sse3-4  float64      181807  0.837222         5                               3.0
20                    general_ema.csv                    EMA\general_ema.csv                            sse3_resp_mean  float64      181807  0.837222     34405                     2.99592399597
21                    general_ema.csv                    EMA\general_ema.csv                          sse3_resp_median  float64      181807  0.837222     33122                     2.98918390274
22                    general_ema.csv                    EMA\general_ema.csv                                    stress  float64      181807  0.837222         5                               1.0
23                    general_ema.csv                    EMA\general_ema.csv                        avg_ema_spent_time  float64      178148  0.820373     38118                     37.3856978416
24  Data Dictionary (general EMA).csv  EMA\Data Dictionary (general EMA).csv                                  Variable      str           0  0.000000        19                               uid
25  Data Dictionary (general EMA).csv  EMA\Data Dictionary (general EMA).csv  Feature Availability -- Android/iOS/All       str           0  0.000000         1                               All
26  Data Dictionary (general EMA).csv  EMA\Data Dictionary (general EMA).csv                               Description      str           0  0.000000        19                    Unique user ID
27  Data Dictionary (general EMA).csv  EMA\Data Dictionary (general EMA).csv                                     Range      str           8  0.421053         4                           1 to 16
28  Data Dictionary (general EMA).csv  EMA\Data Dictionary (general EMA).csv                          Standard Survey?      str           8  0.421053         4   Yes. Photographic Affect Meter.
29                      covid_ema.csv                      EMA\covid_ema.csv                                       uid      str           0  0.000000       181  1ff6d7f34acb354430e7323a35ff7703

In [14]:
column_inventory.to_csv(output_tables / "column_inventory.csv", index=False)

---
## Student Count Investigation

Fresh analysis of unique student IDs across all dataset files.
No assumptions about expected counts, exclusions, or cohort sizes.
Everything is derived from the data itself.

Files examined:
- EMA/general_ema.csv
- EMA/covid_ema.csv
- Sensing/sensing.csv
- Demographics/demographics.csv

In [15]:
# Load raw files with no filtering, no exclusions, no preprocessing
raw_ema   = pd.read_csv(DATA_DIR / "EMA" / "general_ema.csv")
raw_covid = pd.read_csv(DATA_DIR / "EMA" / "covid_ema.csv")
raw_sens  = pd.read_csv(DATA_DIR / "Sensing" / "sensing.csv")
raw_demo  = pd.read_csv(DATA_DIR / "Demographics" / "demographics.csv")

print("Raw file shapes (rows x columns):")
print(f"  general_ema  : {raw_ema.shape}")
print(f"  covid_ema    : {raw_covid.shape}")
print(f"  sensing      : {raw_sens.shape}")
print(f"  demographics : {raw_demo.shape}")

Raw file shapes (rows x columns):
  general_ema  : (217155, 19)
  covid_ema    : (16511, 12)
  sensing      : (216065, 651)
  demographics : (216, 3)

In [16]:
uids_ema   = set(raw_ema["uid"].unique())
uids_covid = set(raw_covid["uid"].unique())
uids_sens  = set(raw_sens["uid"].unique())
uids_demo  = set(raw_demo["uid"].unique())

print("Unique UIDs per file:")
print(f"  general_ema  : {len(uids_ema)}")
print(f"  covid_ema    : {len(uids_covid)}")
print(f"  sensing      : {len(uids_sens)}")
print(f"  demographics : {len(uids_demo)}")

Unique UIDs per file:
  general_ema  : 220
  covid_ema    : 181
  sensing      : 220
  demographics : 216

In [17]:
in_all_four       = uids_ema & uids_covid & uids_sens & uids_demo
in_ema_sens_demo  = uids_ema & uids_sens & uids_demo
in_ema_and_sens   = uids_ema & uids_sens
in_ema_only       = uids_ema - uids_covid - uids_sens - uids_demo
in_demo_only      = uids_demo - uids_ema - uids_covid - uids_sens
in_sens_not_ema   = uids_sens - uids_ema
in_ema_not_demo   = uids_ema - uids_demo
in_demo_not_ema   = uids_demo - uids_ema

print("Set membership analysis:")
print(f"  In all four files             : {len(in_all_four)}")
print(f"  In EMA + sensing + demo       : {len(in_ema_sens_demo)}")
print(f"  In EMA + sensing              : {len(in_ema_and_sens)}")
print(f"  In EMA only (not in others)   : {len(in_ema_only)}")
print(f"  In demographics only          : {len(in_demo_only)}")
print(f"  In sensing but not EMA        : {len(in_sens_not_ema)}")
print(f"  In EMA but not demographics   : {len(in_ema_not_demo)}")
print(f"  In demographics but not EMA   : {len(in_demo_not_ema)}")

Set membership analysis:
  In all four files             : 180
  In EMA + sensing + demo       : 216
  In EMA + sensing              : 220
  In EMA only (not in others)   : 0
  In demographics only          : 0
  In sensing but not EMA        : 0
  In EMA but not demographics   : 4
  In demographics but not EMA   : 0

In [18]:
# Any UID that appears in some files but not others is anomalous
# Print details for every such student
def describe_ema_student(uid, df):
    rows = df[df["uid"] == uid]
    response_cols = ["phq4-1","phq4-2","phq4-3","phq4-4",
                     "sse3-1","sse3-2","sse3-3","sse3-4",
                     "phq4_score","stress","social_level"]
    existing = [c for c in response_cols if c in df.columns]
    has_resp = rows[existing].notna().any(axis=1)
    return {
        "total_rows":        len(rows),
        "completed_surveys": int(has_resp.sum()),
        "first_day":         rows["day"].min(),
        "last_day":          rows["day"].max(),
        "span_days":         len(rows["day"].unique()),
    }

# UIDs in sensing but not in EMA
if in_sens_not_ema:
    print(f"UIDs in sensing but NOT in EMA ({len(in_sens_not_ema)}):")
    for uid in sorted(in_sens_not_ema):
        rows = raw_sens[raw_sens["uid"] == uid]
        print(f"  {uid} | sensing rows: {len(rows)} | "
              f"days: {rows['day'].min()} to {rows['day'].max()}")
else:
    print("No UIDs in sensing but not in EMA.")

print()

# UIDs in demographics but not in EMA
if in_demo_not_ema:
    print(f"UIDs in demographics but NOT in EMA ({len(in_demo_not_ema)}):")
    for uid in sorted(in_demo_not_ema):
        demo_row = raw_demo[raw_demo["uid"] == uid]
        print(f"  {uid}")
        print(f"    Demographics: {demo_row.to_dict('records')}")
else:
    print("No UIDs in demographics but not in EMA.")

print()

# UIDs in EMA but not in demographics
if in_ema_not_demo:
    print(f"UIDs in EMA but NOT in demographics ({len(in_ema_not_demo)}):")
    for uid in sorted(in_ema_not_demo):
        info = describe_ema_student(uid, raw_ema)
        print(f"  {uid} | rows: {info['total_rows']} | "
              f"surveys: {info['completed_surveys']} | "
              f"days: {info['first_day']} to {info['last_day']}")
else:
    print("No UIDs in EMA but not in demographics.")

No UIDs in sensing but not in EMA.

No UIDs in demographics but not in EMA.

UIDs in EMA but NOT in demographics (4):
  8617ddac1f48b148e3683738519b2e7a | rows: 1269 | surveys: 155 | days: 20180925 to 20220704
  df5e798581def8d477316520953b9171 | rows: 2 | surveys: 0 | days: 20171002 to 20171009
  e6d71fe4a3c10b075ae1cf51a2fe6cfd | rows: 4 | surveys: 0 | days: 20181022 to 20181025
  ea716dd032aaa0dcf8bfa36b1811917f | rows: 50 | surveys: 9 | days: 20170907 to 20171026

In [19]:
# For every unique UID in general_ema, count how many rows they have
# and how many are completed surveys
response_cols = ["phq4-1","phq4-2","phq4-3","phq4-4",
                 "sse3-1","sse3-2","sse3-3","sse3-4",
                 "phq4_score","stress","social_level"]
existing_resp = [c for c in response_cols if c in raw_ema.columns]
raw_ema["_has_response"] = raw_ema[existing_resp].notna().any(axis=1)

per_student_ema = (
    raw_ema.groupby("uid")
    .agg(
        total_rows=("uid", "count"),
        completed_surveys=("_has_response", "sum"),
        first_day=("day", "min"),
        last_day=("day", "max"),
    )
    .reset_index()
)
per_student_ema["span_days"] = (
    pd.to_datetime(per_student_ema["last_day"].astype(str), format="%Y%m%d") -
    pd.to_datetime(per_student_ema["first_day"].astype(str), format="%Y%m%d")
).dt.days + 1

print(f"Total unique students in general_ema: {len(per_student_ema)}")
print(f"\nCompleted survey count distribution:")
print(per_student_ema["completed_surveys"].describe().round(1))

# Flag students with very few completed surveys
print(f"\nStudents with 0 completed surveys:")
zero = per_student_ema[per_student_ema["completed_surveys"] == 0]
print(zero[["uid","total_rows","completed_surveys","first_day","last_day","span_days"]].to_string(index=False))

print(f"\nStudents with 1-4 completed surveys:")
few = per_student_ema[
    (per_student_ema["completed_surveys"] > 0) &
    (per_student_ema["completed_surveys"] < 5)
]
print(few[["uid","total_rows","completed_surveys","first_day","last_day","span_days"]].to_string(index=False))

Total unique students in general_ema: 220

Completed survey count distribution:
count    220.0
mean     160.7
std       88.4
min        0.0
25%       94.0
50%      168.5
75%      205.0
max      441.0
Name: completed_surveys, dtype: float64

Students with 0 completed surveys:
                             uid  total_rows  completed_surveys  first_day  last_day  span_days
df5e798581def8d477316520953b9171           2                  0   20171002  20171009          8
e6d71fe4a3c10b075ae1cf51a2fe6cfd           4                  0   20181022  20181025          4

Students with 1-4 completed surveys:
                             uid  total_rows  completed_surveys  first_day  last_day  span_days
ad15fc229da933fbf1fc0f92fc9b55a3           2                  1   20180923  20180924          2

In [20]:
# How many sensing rows does each UID have, and what is their date range
per_student_sens = (
    raw_sens.groupby("uid")
    .agg(
        total_rows=("uid", "count"),
        first_day=("day", "min"),
        last_day=("day", "max"),
    )
    .reset_index()
)

print(f"Total unique students in sensing: {len(per_student_sens)}")
print(f"\nRow count distribution:")
print(per_student_sens["total_rows"].describe().round(1))

# Flag students with very few sensing rows
few_sens = per_student_sens[per_student_sens["total_rows"] < 10]
if not few_sens.empty:
    print(f"\nStudents with fewer than 10 sensing rows:")
    print(few_sens.to_string(index=False))
else:
    print("\nNo students with fewer than 10 sensing rows.")

Total unique students in sensing: 220

Row count distribution:
count     220.0
mean      982.1
std       381.5
min         2.0
25%       749.0
50%      1143.5
75%      1280.8
max      1370.0
Name: total_rows, dtype: float64

Students with fewer than 10 sensing rows:
                             uid  total_rows  first_day  last_day
ad15fc229da933fbf1fc0f92fc9b55a3           2   20180923  20180924
df5e798581def8d477316520953b9171           2   20171002  20171009
e6d71fe4a3c10b075ae1cf51a2fe6cfd           4   20181022  20181025

In [21]:
# Build a matrix showing which files each UID appears in
all_uids = uids_ema | uids_covid | uids_sens | uids_demo

presence = pd.DataFrame({
    "uid":         list(all_uids),
    "in_ema":      [uid in uids_ema   for uid in all_uids],
    "in_covid":    [uid in uids_covid for uid in all_uids],
    "in_sensing":  [uid in uids_sens  for uid in all_uids],
    "in_demo":     [uid in uids_demo  for uid in all_uids],
})
presence["files_count"] = (
    presence[["in_ema","in_covid","in_sensing","in_demo"]]
    .sum(axis=1)
)

print("Presence matrix summary:")
print(presence.groupby(
    ["in_ema","in_covid","in_sensing","in_demo"]
).size().reset_index(name="n_students").to_string(index=False))

print(f"\nUIDs present in all 4 files    : {(presence['files_count']==4).sum()}")
print(f"UIDs present in exactly 3 files : {(presence['files_count']==3).sum()}")
print(f"UIDs present in exactly 2 files : {(presence['files_count']==2).sum()}")
print(f"UIDs present in exactly 1 file  : {(presence['files_count']==1).sum()}")

# Print the anomalous ones (not in all files)
anomalous = presence[presence["files_count"] < 4]
if not anomalous.empty:
    print(f"\nUIDs NOT present in all four files ({len(anomalous)}):")
    print(anomalous.to_string(index=False))

Presence matrix summary:
 in_ema  in_covid  in_sensing  in_demo  n_students
   True     False        True    False           3
   True     False        True     True          36
   True      True        True    False           1
   True      True        True     True         180

UIDs present in all 4 files    : 180
UIDs present in exactly 3 files : 37
UIDs present in exactly 2 files : 3
UIDs present in exactly 1 file  : 0

UIDs NOT present in all four files (40):
                             uid  in_ema  in_covid  in_sensing  in_demo  files_count
07eab8e219b6a4dcd45167dc216e1189    True     False        True     True            3
c0b0998fe60a905081764378d1102494    True     False        True     True            3
76b564dca3ab4d899e5a30d3cbcb0aac    True     False        True     True            3
3528757eaf1d15ee6c778eb79cd02de7    True     False        True     True            3
ac70fe1f8115ac361f2023269c011c3e    True     False        True     True            3
596df3c263e97eb09d44a8535ec20ffa    True     False        True     True            3
f1dcebbb6fbe6d586ddb2c43c781e013    True     False        True     True            3
8feafc5db9bf59d00a21335e69b57804    True     False        True     True            3
165970c3847523de7691ef9766b0f3f4    True     False        True     True            3
ea716dd032aaa0dcf8bfa36b1811917f    True     False        True    False            2
12e0a85ee9819ae1abeca0ccfaa52d13    True     False        True     True            3
1badfae62cc1b76787d4f8beb68737bf    True     False        True     True            3
4b5eb55e64b6bc941796bf114149cab7    True     False        True     True            3
e6d71fe4a3c10b075ae1cf51a2fe6cfd    True     False        True    False            2
ab5ee451ce580a761fefd88f7b49a97f    True     False        True     True            3
56b90ef8a34e80ebc086ecd8d594e9d8    True     False        True     True            3
a4dde9659b38b613f08b37c0c8bfa9eb    True     False        True     True            3
1e85c892d8f047ff621ad9134c4e6d8d    True     False        True     True            3
24e89780f6c9efef9ab28fea842cf620    True     False        True     True            3
da130c5ecc942e7cd705585222a42adf    True     False        True     True            3
91d30de367a6a0772fdca55ec5b129a2    True     False        True     True            3
0aee9faa6f2d2d24d85d2690f5b2df25    True     False        True     True            3
db8df8be53722b041b1e649ae0c0b5d4    True     False        True     True            3
ad15fc229da933fbf1fc0f92fc9b55a3    True     False        True     True            3
8617ddac1f48b148e3683738519b2e7a    True      True        True    False            3
c21d2515be8477a92181b9c0035a9884    True     False        True     True            3
703c70ff9f0c7a8e24757d0270a2e932    True     False        True     True            3
8733d6d19519598608c6dc2f9ee525d7    True     False        True     True            3
1893420fc2b045e14ef0112c1b079afe    True     False        True     True            3
690d25f3b083e647278ed85c6bb033ae    True     False        True     True            3
8479552e5849c2f93e5f8ab1720ed78b    True     False        True     True            3
fbcc8cd8254960ed44ffdd3390a2f6a0    True     False        True     True            3
50e32d5c464c892af7aa4b6a666e876d    True     False        True     True            3
1c12f39481a6c09da17bd4e6bebed9a2    True     False        True     True            3
df5e798581def8d477316520953b9171    True     False        True    False            2
9e9e21ee5dbdb37ffda3225cd0403d34    True     False        True     True            3
98e5152e1020930fb007145c1c60648b    True     False        True     True            3
c4de76cb7f30c4073617bfb80fabaec6    True     False        True     True            3
01fb41df0f6c2f69d65db5a38c600b4c    True     False        True     True            3
46f1dfeda71a865074859c81bb314fd9    True     False        True     True            3

In [22]:
# For each UID that is anomalous in any way, describe why
# This produces the definitive exclusion decision table
decisions = []

for uid in sorted(all_uids):
    in_ema     = uid in uids_ema
    in_covid   = uid in uids_covid
    in_sensing = uid in uids_sens
    in_demo    = uid in uids_demo

    ema_info = describe_ema_student(uid, raw_ema) if in_ema else {}
    total     = ema_info.get("total_rows", 0)
    surveys   = ema_info.get("completed_surveys", 0)
    span      = ema_info.get("span_days", 0)

    # Classify reason
    if not in_ema:
        reason = "not_in_ema"
    elif not in_sensing:
        reason = "not_in_sensing"
    elif not in_demo:
        reason = "not_in_demographics"
    elif surveys == 0:
        reason = "zero_completed_surveys"
    elif surveys < 5:
        reason = f"very_few_surveys_{surveys}"
    elif span < 30:
        reason = f"very_short_span_{span}_days"
    else:
        reason = "ok"

    if reason != "ok":
        decisions.append({
            "uid":         uid,
            "in_ema":      in_ema,
            "in_covid":    in_covid,
            "in_sensing":  in_sensing,
            "in_demo":     in_demo,
            "total_rows":  total,
            "surveys":     surveys,
            "span_days":   span,
            "reason":      reason,
        })

decisions_df = pd.DataFrame(decisions)
print(f"UIDs flagged as anomalous: {len(decisions_df)}")
if not decisions_df.empty:
    print(decisions_df.to_string(index=False))

UIDs flagged as anomalous: 5
                             uid  in_ema  in_covid  in_sensing  in_demo  total_rows  surveys  span_days              reason
8617ddac1f48b148e3683738519b2e7a    True      True        True    False        1269      155       1269 not_in_demographics
ad15fc229da933fbf1fc0f92fc9b55a3    True     False        True     True           2        1          2  very_few_surveys_1
df5e798581def8d477316520953b9171    True     False        True    False           2        0          2 not_in_demographics
e6d71fe4a3c10b075ae1cf51a2fe6cfd    True     False        True    False           4        0          4 not_in_demographics
ea716dd032aaa0dcf8bfa36b1811917f    True     False        True    False          50        9         50 not_in_demographics

In [23]:
# Derive final usable population from evidence, not assumptions
ok_uids = all_uids - set(decisions_df["uid"].tolist())

print("=" * 55)
print("STUDENT COUNT SUMMARY - DERIVED FROM DATA")
print("=" * 55)
print(f"  Total unique UIDs across all files : {len(all_uids)}")
print(f"  UIDs in general_ema                : {len(uids_ema)}")
print(f"  UIDs in sensing                    : {len(uids_sens)}")
print(f"  UIDs in covid_ema                  : {len(uids_covid)}")
print(f"  UIDs in demographics               : {len(uids_demo)}")
print()
print(f"  Flagged as anomalous               : {len(decisions_df)}")
print(f"  Usable population (ok UIDs)        : {len(ok_uids)}")
print()
print("Anomalous UIDs breakdown:")
if not decisions_df.empty:
    for _, row in decisions_df.iterrows():
        print(f"  {row['uid'][:8]}...  reason: {row['reason']}")

# Save the decisions table
decisions_df.to_csv(
    "../../outputs/tables/uid_exclusion_decisions.csv",
    index=False
)
print("\nSaved to outputs/tables/uid_exclusion_decisions.csv")

=======================================================
STUDENT COUNT SUMMARY - DERIVED FROM DATA
=======================================================
  Total unique UIDs across all files : 220
  UIDs in general_ema                : 220
  UIDs in sensing                    : 220
  UIDs in covid_ema                  : 181
  UIDs in demographics               : 216

  Flagged as anomalous               : 5
  Usable population (ok UIDs)        : 215

Anomalous UIDs breakdown:
  8617ddac...  reason: not_in_demographics
  ad15fc22...  reason: very_few_surveys_1
  df5e7985...  reason: not_in_demographics
  e6d71fe4...  reason: not_in_demographics
  ea716dd0...  reason: not_in_demographics

Saved to outputs/tables/uid_exclusion_decisions.csv